name: statemanagement_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_riverpod: ^2.0.2
  flutter_errors:
    git:
      url: https://github.com/faiyyazs/flutter-errors.git
      ref: main
      path: flutter-errors/

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
  analyzer: 4.7.0

flutter: