name: network_retrofit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  get_it:
  injectable:
  dependency_injection:
    path: ../../dependency-injection/
  data:
    path: ../../core/data/
  dio:
  retrofit: '>=3.0.0 <4.0.0'
  logger: any  #for logging purpose
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  injectable_generator: ^1.5.3
  build_runner: ^2.2.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'
