name: CI
on:
  pull_request:
jobs:
  lint-test-build-android:
    name: Lint, Test And Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Install Tools'
        run: |
            ./.github/workflows/scripts/install-tools.sh

      - name: 'Bootstrap Workspace'
        run: melos bootstrap

      - name: Setup app_secrets.dart
        env:
          APP_SECRETS: ${{ secrets.APP_SECRETS }}
          APP_SECRETS_PATH: app/lib/secrets/app_secrets.dart
        run: echo -n $APP_SECRETS | base64 --decode > $APP_SECRETS_PATH

      - name: Get Dependencies
        run: melos run get

      - name: Run build_runner
        run: melos run generate

      - name: Lint
        run: melos run analyze

#      - name: Unit tests
#        run: melos run test-golden

      - name: Build Android
        run: scripts/build.sh apk dev --debug
        working-directory: app/


  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [ lint-test-build-android ]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Install Tools'
        run: |
            ./.github/workflows/scripts/install-tools.sh

      - name: 'Bootstrap Workspace'
        run: melos bootstrap

      - name: Setup app_secrets.dart
        env:
          APP_SECRETS: ${{ secrets.APP_SECRETS }}
          APP_SECRETS_PATH: app/lib/secrets/app_secrets.dart
        run: echo -n $APP_SECRETS | base64 --decode > $APP_SECRETS_PATH

      - name: Get Dependencies
        run: melos run get

      - name: Run build_runner
        run: melos run generate

#      - name: Golden tests
#        run: melos run test-golden

      - name: Build iOS
        run: scripts/build.sh ios dev --debug --no-codesign
        working-directory: app/